// Regenerate src/templates.rs from templates/changelog.truss via the v1 emitter.
// (Same pattern as examples/blog; the committed module is the v1 stand-in for the
// v2 proc-macro.)  Run: node trussbars/examples/changelog/generate.mjs

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "../../..");
const { compileMaxRust } = await import(resolve(root, "output/MaxBars.Rust/index.js"));

const src = readFileSync(resolve(here, "templates/changelog.truss"), "utf8");
const r = compileMaxRust("ChangelogCtx")(src);
if (!r.ok) {
  console.error(`error: changelog.truss did not compile: ${r.err}`);
  process.exit(1);
}
const body = r.out.replace(
  /^pub fn render\(ctx: &ChangelogCtx\)/m,
  "pub fn render_changelog(ctx: &ChangelogCtx)",
);

writeFileSync(
  resolve(here, "src/templates.rs"),
  `// @generated by generate.mjs from templates/changelog.truss — DO NOT EDIT.
// Regenerate: \`node trussbars/examples/changelog/generate.mjs\` (needs the spago build).
#![allow(clippy::needless_borrow, clippy::single_char_add_str)] // machine-generated
use crate::context::ChangelogCtx;

${body}`,
);
console.log("wrote src/templates.rs");
