// @generated by generate.mjs from templates/*.truss — DO NOT EDIT.
// Regenerate: `node trussbars/examples/blog/generate.mjs` (needs the spago build).
// These are the VERBATIM render functions the Trussbars v1 emitter produces; they
// link against trussbars-core (output) and trussbars-std (groupBy).
// Machine-generated: the v1 emitter wraps args uniformly in `&(…)` and pushes
// single-char literals, which clippy flags but a hand-writer wouldn't (v2 codegen
// will be type-aware and cleaner — see the README).
#![allow(clippy::needless_borrow, clippy::single_char_add_str)]
use crate::context::{ArchiveCtx, IndexCtx, PostCtx};

// ── index.truss ──
pub fn render_index(ctx: &IndexCtx) -> String {
    static __CAP: trussbars_core::SizeHint = trussbars_core::SizeHint::new(390);
    let __root = ctx;
    let mut out = String::with_capacity(__CAP.suggest());
    out.push_str("<h1>");
    // index.truss:1:5  {{site.title}}
    trussbars_core::esc(&(ctx.site.title), &mut out);
    out.push_str("</h1>\n<nav>");
    // index.truss:2:6  {{#each ["All", "Rust", "Design"]}}
    {
        let __sub1 = &(["All", "Rust", "Design"]);
        let __len1 = trussbars_core::Each::each_len(__sub1);
        if __len1 == 0 {
        } else {
            for (__i1, (__k1, __c1)) in trussbars_core::Each::each(__sub1).enumerate() {
                let __l1 = trussbars_core::Loop::at(__i1, __len1, __k1, None);
                out.push_str("<a href=\"/tag/");
                // index.truss:2:55  {{this | lowercase}}
                trussbars_core::esc(&(trussbars_std::lowercase(&(__c1))), &mut out);
                out.push_str("\">");
                // index.truss:2:77  {{this}}
                trussbars_core::esc(&(__c1), &mut out);
                out.push_str("</a> ");
            }
        }
    }
    out.push_str("</nav>\n");
    // index.truss:9:12  {{#each posts}}
    {
        let __sub1 = &(ctx.posts);
        let __len1 = trussbars_core::Each::each_len(__sub1);
        if __len1 == 0 {
        } else {
            for (__i1, (__k1, __c1)) in trussbars_core::Each::each(__sub1).enumerate() {
                let __l1 = trussbars_core::Loop::at(__i1, __len1, __k1, None);
                // index.truss:9:27  {{> card}}
                out.push_str("<article>\n  <h2><a href=\"/posts/");
                // index.truss:4:23  {{slug}}
                trussbars_core::esc(&(__c1.slug), &mut out);
                out.push_str("\">");
                // index.truss:4:33  {{title}}
                trussbars_core::esc(&(__c1.title), &mut out);
                out.push_str("</a></h2>\n  <p class=\"meta\">by ");
                // index.truss:5:22  {{author}}
                trussbars_core::esc(&(__c1.author), &mut out);
                // index.truss:5:32  {{#if views > 100}}
                if trussbars_core::truthy(&(__c1.views > 100.0)) {
                    out.push_str(" · 🔥 popular");
                }
                out.push_str("</p>\n  ");
                // index.truss:6:3  {{#if tags}}
                if trussbars_core::truthy(&(__c1.tags)) {
                    out.push_str("<p class=\"tags\">");
                    // index.truss:6:31  {{#each tag in tags}}
                    {
                        let __sub2 = &(__c1.tags);
                        let __len2 = trussbars_core::Each::each_len(__sub2);
                        if __len2 == 0 {
                        } else {
                            for (__i2, (__k2, __c2)) in
                                trussbars_core::Each::each(__sub2).enumerate()
                            {
                                let __l2 = trussbars_core::Loop::at(__i2, __len2, __k2, None);
                                out.push_str("<a href=\"/tags/");
                                // index.truss:6:67  {{tag | lowercase}}
                                trussbars_core::esc(&(trussbars_std::lowercase(&(__c2))), &mut out);
                                out.push_str("\">#");
                                // index.truss:6:89  {{tag}}
                                trussbars_core::esc(&(__c2), &mut out);
                                out.push_str("</a> ");
                            }
                        }
                    }
                    out.push_str("</p>");
                }
                out.push_str("\n  <p>");
                // index.truss:7:6  {{excerpt}}
                trussbars_core::esc(&(__c1.excerpt), &mut out);
                out.push_str("</p>\n</article>\n");
            }
        }
    }
    __CAP.record(out.len());
    out
}

// ── post.truss ──
pub fn render_post(ctx: &PostCtx) -> String {
    static __CAP: trussbars_core::SizeHint = trussbars_core::SizeHint::new(468);
    let __root = ctx;
    let mut out = String::with_capacity(__CAP.suggest());
    out.push_str("<article>\n  <h1>");
    // post.truss:2:7  {{post.title}}
    trussbars_core::esc(&(ctx.post.title), &mut out);
    out.push_str("</h1>\n  <p class=\"meta\">by ");
    // post.truss:3:22  {{post.author}}
    trussbars_core::esc(&(ctx.post.author), &mut out);
    out.push_str(" · ");
    // post.truss:3:40  {{post.date}}
    trussbars_core::esc(&(ctx.post.date), &mut out);
    out.push_str(" · ");
    // post.truss:3:56  {{post.tags | count}}
    trussbars_core::esc(&(trussbars_std::count(&(ctx.post.tags))), &mut out);
    out.push_str(" tags</p>\n  <div class=\"body\">");
    // post.truss:4:21  {{{post.body_html}}}
    trussbars_core::ToText::write_text(&(ctx.post.body_html), &mut out);
    out.push_str("</div>\n  <footer>");
    // post.truss:5:11  {{#each tag in post.tags}}
    {
        let __sub1 = &(ctx.post.tags);
        let __len1 = trussbars_core::Each::each_len(__sub1);
        if __len1 == 0 {
        } else {
            for (__i1, (__k1, __c1)) in trussbars_core::Each::each(__sub1).enumerate() {
                let __l1 = trussbars_core::Loop::at(__i1, __len1, __k1, None);
                out.push_str("<a href=\"/tags/");
                // post.truss:5:52  {{tag | lowercase}}
                trussbars_core::esc(&(trussbars_std::lowercase(&(__c1))), &mut out);
                out.push_str("\">#");
                // post.truss:5:74  {{tag}}
                trussbars_core::esc(&(__c1), &mut out);
                out.push_str("</a> ");
            }
        }
    }
    out.push_str("</footer>\n</article>");
    __CAP.record(out.len());
    out
}

// ── archive.truss ──
pub fn render_archive(ctx: &ArchiveCtx) -> String {
    static __CAP: trussbars_core::SizeHint = trussbars_core::SizeHint::new(3596);
    let __root = ctx;
    let mut out = String::with_capacity(__CAP.suggest());
    out.push_str("<h1>");
    // archive.truss:1:5  {{site.title}}
    trussbars_core::esc(&(ctx.site.title), &mut out);
    out.push_str(" — Archive</h1>\n");
    // archive.truss:2:1  {{#each (groupBy posts "year")}}
    {
        let __sub1 = &(trussbars_std::group_by(&(ctx.posts), |__x| {
            let mut __s = String::new();
            trussbars_core::ToText::write_text(&__x.year, &mut __s);
            __s
        }));
        let __len1 = trussbars_core::Each::each_len(__sub1);
        if __len1 == 0 {
        } else {
            for (__i1, (__k1, __c1)) in trussbars_core::Each::each(__sub1).enumerate() {
                let __l1 = trussbars_core::Loop::at(__i1, __len1, __k1, None);
                // archive.truss:2:33  {{#let n=(this | count)}}
                {
                    let __let_n = trussbars_std::count(&(__c1));
                    out.push_str("<section>\n  <h2>");
                    // archive.truss:3:7  {{loop.key}}
                    trussbars_core::esc(&(__l1.key), &mut out);
                    out.push_str(" (");
                    // archive.truss:3:21  {{n}}
                    trussbars_core::esc(&(__let_n), &mut out);
                    out.push_str(" posts)</h2>\n  <ul>");
                    // archive.truss:4:7  {{#each post in this}}
                    {
                        let __sub2 = &(__c1);
                        let __len2 = trussbars_core::Each::each_len(__sub2);
                        if __len2 == 0 {
                        } else {
                            for (__i2, (__k2, __c2)) in
                                trussbars_core::Each::each(__sub2).enumerate()
                            {
                                let __l2 =
                                    trussbars_core::Loop::at(__i2, __len2, __k2, Some(&__l1));
                                out.push_str("<li><a href=\"/posts/");
                                // archive.truss:4:49  {{post.slug}}
                                trussbars_core::esc(&(__c2.slug), &mut out);
                                out.push_str("\">");
                                // archive.truss:4:64  {{post.title}}
                                trussbars_core::esc(&(__c2.title), &mut out);
                                out.push_str("</a></li>");
                            }
                        }
                    }
                    out.push_str("</ul>\n</section>\n");
                }
            }
        }
    }
    __CAP.record(out.len());
    out
}
