// @generated by generate.mjs from templates/changelog.truss — DO NOT EDIT.
// Regenerate: `node trussbars/examples/changelog/generate.mjs` (needs the spago build).
#![allow(clippy::needless_borrow, clippy::single_char_add_str)] // machine-generated
use crate::context::ChangelogCtx;

pub fn render_changelog(ctx: &ChangelogCtx) -> String {
    static __CAP: trussbars_core::SizeHint = trussbars_core::SizeHint::new(3063);
    let __root = ctx;
    let mut out = String::with_capacity(__CAP.suggest());
    out.push_str("# ");
    trussbars_core::esc(&(ctx.project), &mut out);
    out.push_str(" — Changelog\n");
    {
        let __sub1 = &(trussbars_std::group_by(&(ctx.commits), |__x| {
            let mut __s = String::new();
            trussbars_core::ToText::write_text(&__x.category, &mut __s);
            __s
        }));
        let __len1 = trussbars_core::Each::each_len(__sub1);
        if __len1 == 0 {
        } else {
            for (__i1, (__k1, __c1)) in trussbars_core::Each::each(__sub1).enumerate() {
                let __l1 = trussbars_core::Loop::at(__i1, __len1, __k1, None);
                out.push_str("## ");
                trussbars_core::esc(&(__l1.key), &mut out);
                out.push_str("\n");
                {
                    let __sub2 = &(__c1);
                    let __len2 = trussbars_core::Each::each_len(__sub2);
                    if __len2 == 0 {
                    } else {
                        for (__i2, (__k2, __c2)) in trussbars_core::Each::each(__sub2).enumerate() {
                            let __l2 = trussbars_core::Loop::at(__i2, __len2, __k2, Some(&__l1));
                            out.push_str("- ");
                            trussbars_core::esc(&(__c2.subject), &mut out);
                            if trussbars_core::truthy(&(__c2.scope)) {
                                out.push_str(" _(");
                                trussbars_core::esc(&(__c2.scope), &mut out);
                                out.push_str(")_");
                            }
                            out.push_str(" `");
                            trussbars_core::esc(&(__c2.hash), &mut out);
                            out.push_str("` · ");
                            trussbars_core::esc(&(__c2.date), &mut out);
                            out.push_str("\n");
                        }
                    }
                }
                out.push_str("");
            }
        }
    }
    __CAP.record(out.len());
    out
}
