// Regenerate src/templates.rs from templates/*.truss using the v1 Trussbars
// emitter (`compileMaxRust` from the spago build). This is the moral equivalent
// of what the v2 proc-macro will do at compile time; for the v1 example we commit
// the generated module so the crate builds with plain `cargo` (no PureScript
// toolchain at build time).
//
//   node trussbars/examples/blog/generate.mjs      # rewrites src/templates.rs
//
// Requires `output/` (run `npx spago build` at the repo root first).

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "../../..");
const { compileMaxRust } = await import(resolve(root, "output/MaxBars.Rust/index.js"));

// (template file, emitted fn name, host context type).
const PAGES = [
  { file: "index.truss", fn: "render_index", ctx: "IndexCtx" },
  { file: "post.truss", fn: "render_post", ctx: "PostCtx" },
  { file: "archive.truss", fn: "render_archive", ctx: "ArchiveCtx" },
];

const modules = [];
for (const p of PAGES) {
  const src = readFileSync(resolve(here, "templates", p.file), "utf8");
  const r = compileMaxRust(p.ctx)(src);
  if (!r.ok) {
    console.error(`error: ${p.file} did not compile: ${r.err}`);
    process.exit(1);
  }
  // Rename the emitted `render` to the page-specific name.
  const body = r.out.replace(
    new RegExp(`^pub fn render\\(ctx: &${p.ctx}\\)`, "m"),
    `pub fn ${p.fn}(ctx: &${p.ctx})`,
  );
  modules.push(`// ── ${p.file} ──\n${body}`);
}

const out = `// @generated by generate.mjs from templates/*.truss — DO NOT EDIT.
// Regenerate: \`node trussbars/examples/blog/generate.mjs\` (needs the spago build).
// These are the VERBATIM render functions the Trussbars v1 emitter produces; they
// link against trussbars-core (output) and trussbars-std (groupBy).
use crate::context::{ArchiveCtx, IndexCtx, PostCtx};

${modules.join("\n\n")}
`;

writeFileSync(resolve(here, "src/templates.rs"), out);
console.log(`wrote src/templates.rs (${PAGES.length} pages)`);
