// SPDX-License-Identifier: Apache-2.0
//
// VENDORED per-surface syntax/policy deltas for the FlatBars Lab's surface-aware
// Reference popup. A pure projection of shared/surface-syntax.json — generated by
// scripts/gen-surface-syntax.mjs, drift-gated by check:surface-syntax. DO NOT EDIT;
// run `npm run gen:surface-syntax`. (Prod deploys only lab/, so the Lab cannot read
// shared/ at runtime — this projection is how the single source reaches it.)
export const SURFACE_SYNTAX = [
  {
    "id": "rawbars",
    "label": "RawBars",
    "engine": "rawbars",
    "route": "/rawbars",
    "tagline": "The desugared core surface — core skeleton syntax, no sugar.",
    "compiles": true,
    "truthiness": {
      "rule": "nonEmpty",
      "falsy": "false  null  \"\"  []  {}",
      "note": "0 is truthy; empty containers are falsy"
    },
    "rows": [
      {
        "feature": "Output (raw only)",
        "syntax": "{{{value}}}",
        "note": "Triple-stash only; no {{ }} auto-escape shorthand.",
        "kind": "only"
      },
      {
        "feature": "Field access",
        "syntax": "{{{(lookup this \"city\")}}}",
        "note": "Explicit lookup helper; no dotted-path sugar.",
        "kind": "only"
      },
      {
        "feature": "Escaping",
        "syntax": "{{{(escapeHtml x)}}}",
        "note": "Manual — escaping is a helper, never implicit.",
        "kind": "shared"
      },
      {
        "feature": "Subexpressions",
        "syntax": "(upcase (lookup this \"name\"))",
        "note": "Parens group a nested application into one argument.",
        "kind": "shared"
      },
      {
        "feature": "Blocks",
        "syntax": "{{#each xs}} … {{/each}}",
        "note": "Core block; head is a helper application.",
        "kind": "shared"
      },
      {
        "feature": "Inverse",
        "syntax": "{{#unless ok}} … {{/unless}}",
        "note": "Inverse via the unless helper — no {{^}} sigil.",
        "kind": "shared"
      },
      {
        "feature": "Loop variables",
        "syntax": "{{{index}}}  {{{first}}}  {{{key}}}",
        "note": "Bare scoped ops: index, key, first, last, length. No @-data.",
        "kind": "only"
      },
      {
        "feature": "Comments",
        "syntax": "{{! editorial note }}",
        "note": "Dropped by the lexer.",
        "kind": "shared"
      },
      {
        "feature": "Partials",
        "syntax": "{{{(partial \"name\" this)}}}",
        "note": "Called as the partial helper, unescaped.",
        "kind": "only"
      }
    ]
  },
  {
    "id": "fullbars",
    "label": "FullBars",
    "engine": "fullbars",
    "route": "/fullbars",
    "tagline": "The Handlebars-faithful surface — auto-escape, dotted paths, @-data.",
    "compiles": true,
    "truthiness": {
      "rule": "handlebars",
      "falsy": "false  null  0  \"\"  []",
      "note": "{} is truthy; 0 is falsy unless includeZero=true"
    },
    "rows": [
      {
        "feature": "Output (auto-escape)",
        "syntax": "{{value}}",
        "note": "{{ }} auto-escapes; {{{ }}} or {{&value}} for raw.",
        "kind": "shared"
      },
      {
        "feature": "Path access",
        "syntax": "{{user.address.city}}",
        "note": "Dotted paths, parent climb ../x, and @root.",
        "kind": "shared"
      },
      {
        "feature": "Block params",
        "syntax": "{{#each xs as |item i|}}",
        "note": "Rename the loop bindings.",
        "kind": "shared"
      },
      {
        "feature": "Subexpressions",
        "syntax": "{{upcase (concat a b)}}",
        "note": "Parens group nested applications.",
        "kind": "shared"
      },
      {
        "feature": "@-data variables",
        "syntax": "{{@index}}  {{@key}}  {{@root}}",
        "note": "Scoped data installed by each / with.",
        "kind": "only"
      },
      {
        "feature": "Partials",
        "syntax": "{{> sidebar}}   {{> (lookup this \"p\")}}",
        "note": "Surface sugar; desugars to the partial helper.",
        "kind": "shared"
      },
      {
        "feature": "Else / inverse",
        "syntax": "{{#each xs}} … {{else}} … {{/each}}",
        "note": "{{else}} separator; {{^x}} inverted section.",
        "kind": "shared"
      },
      {
        "feature": "Long comments",
        "syntax": "{{!-- note with }} inside --}}",
        "note": "Handles }} within the comment body.",
        "kind": "shared"
      }
    ]
  },
  {
    "id": "maxbars",
    "label": "MaxBars",
    "engine": "maxbars",
    "route": "/maxbars",
    "tagline": "The flagship — FullBars plus infix operators and pipes.",
    "compiles": true,
    "truthiness": {
      "rule": "nonEmpty",
      "falsy": "false  null  \"\"  []  {}",
      "note": "0 is truthy; same rule as RawBars"
    },
    "rows": [
      {
        "feature": "Infix operators",
        "syntax": "{{price * qty}}   {{score >= 90}}",
        "note": "Desugar to helpers: multiply, gte, and, or, not, coalesce.",
        "kind": "only"
      },
      {
        "feature": "Pipes",
        "syntax": "{{name | upcase | truncate 8}}",
        "note": "Left value becomes the helper's first argument.",
        "kind": "only"
      },
      {
        "feature": "Boolean / coalesce",
        "syntax": "{{a && b}}   {{a ?? fallback}}",
        "note": "&& || ! ?? as infix; group with parens.",
        "kind": "only"
      },
      {
        "feature": "Path access",
        "syntax": "{{user.city}}   {{root.x}}   {{parent.x}}",
        "note": "Reserved names instead of @root / ../  (no @-sigil).",
        "kind": "only"
      },
      {
        "feature": "Loop variables",
        "syntax": "{{index0}}   {{loop.first}}   {{outer.index0}}",
        "note": "Bare scoped ops or labelled loop / outer chains (ADR-021).",
        "kind": "only"
      },
      {
        "feature": "Block params",
        "syntax": "{{#each xs as |item i|}}",
        "note": "The as |…| bars are distinct from the pipe operator.",
        "kind": "shared"
      },
      {
        "feature": "Output (auto-escape)",
        "syntax": "{{value}}  /  {{{value}}}",
        "note": "Inherits the FullBars escape model.",
        "kind": "shared"
      },
      {
        "feature": "Inline / block partials",
        "syntax": "{{#inline \"name\"}} … {{/inline}}   {{yield}}",
        "note": "Bare yield (no @partial-block); rejects {{^}} and {{#*inline}}.",
        "kind": "only"
      }
    ]
  },
  {
    "id": "minbars",
    "label": "MinBars",
    "engine": "minbars",
    "route": "/minbars",
    "tagline": "Mustache-compatible — logic-less, sections, set-delimiters.",
    "compiles": false,
    "truthiness": {
      "rule": "mustache-spec",
      "falsy": "false  null  []",
      "note": "0, \"\", {} are all truthy (the language-agnostic spec rule)"
    },
    "rows": [
      {
        "feature": "Output (auto-escape)",
        "syntax": "{{value}}   {{{value}}}   {{&value}}",
        "note": "{{ }} escapes; {{{ }}} and {{&}} are raw.",
        "kind": "shared"
      },
      {
        "feature": "Sections",
        "syntax": "{{#items}} … {{/items}}",
        "note": "Shape decides: list iterates, truthy shows once.",
        "kind": "shared"
      },
      {
        "feature": "Inverted sections",
        "syntax": "{{^items}} none {{/items}}",
        "note": "Renders when the value is falsy / empty.",
        "kind": "shared"
      },
      {
        "feature": "Implicit iterator",
        "syntax": "{{.}}",
        "note": "The current scalar inside an array section.",
        "kind": "only"
      },
      {
        "feature": "Set delimiters",
        "syntax": "{{=<% %>=}} … <% x %> … <%={{ }}=%>",
        "note": "Switch the active pair mid-template — MinBars only (ADR-015).",
        "kind": "only"
      },
      {
        "feature": "Partials",
        "syntax": "{{> header}}",
        "note": "Standalone; no context override in base Mustache.",
        "kind": "shared"
      },
      {
        "feature": "Inheritance",
        "syntax": "{{<base}} {{$block}} … {{/block}} {{/base}}",
        "note": "Parent / block-override template inheritance.",
        "kind": "only"
      },
      {
        "feature": "Comments",
        "syntax": "{{! note }}",
        "note": "Dropped by the lexer.",
        "kind": "shared"
      }
    ]
  }
];
